networks:
  app-network:
    driver: bridge

volumes:
  db-data:
    driver: local
  minio-data:
    driver: local

services:
  app:
    build:
      context: .
    container_name: delivery
    networks:
      - app-network
    depends_on:
      - db
      - minio
    env_file:
      - .env
    ports:
      - '8080:8080'

  db:
    image: postgres:15.1-alpine
    container_name: postgres
    networks:
      - app-network
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    ports:
      - '1515:5432'
    volumes:
      - ./src/main/resources/db/init:/docker-entrypoint-initdb.d
      - db-data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: minio
    networks:
      - app-network
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
    command: server ~/minio --console-address :9090
    ports:
      - '9090:9090'
      - '9000:9000'
    volumes:
      - minio-data:/minio

